name = "hello-ai"
main = "src/index.ts"
compatibility_date = "2025-11-05"

[site]
bucket = "./public"

[[kv_namespaces]]
binding = "ASSETS"
id = "9b6cce9e90644ff28a2cff2c113811ca"
preview_id = "4a452d73838945b5a3065ef63c68d951"

[ai]
binding = "AI"

[dev]
port = 8787
ip = "127.0.0.1"
